# -*- coding: utf-8 -*-
"""WEEK7_Q5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xYL82MPrDCHqG6nuGDzRug93xHfuCBHa
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Set professional style
sns.set_style("whitegrid")
sns.set_context("talk")

# Generate synthetic customer analytics data
np.random.seed(42)
segments = ["High-Value", "Mid-Tier", "Budget"]
data = {
    "Segment": np.repeat(segments, 200),
    "PurchaseAmount": np.concatenate([
        np.random.normal(loc=500, scale=120, size=200),  # High-Value customers
        np.random.normal(loc=250, scale=80, size=200),   # Mid-Tier customers
        np.random.normal(loc=100, scale=40, size=200)    # Budget customers
    ])
}
df = pd.DataFrame(data)

# Create figure for exact 512x512 px (8x8 in at 64 dpi)
plt.figure(figsize=(8, 8))

# Boxplot
sns.boxplot(
    data=df,
    x="Segment",
    y="PurchaseAmount",
    palette="Set2"
)

# Titles and labels
plt.title("Purchase Amount Distribution by Customer Segment", fontsize=16, weight="bold")
plt.xlabel("Customer Segment", fontsize=14)
plt.ylabel("Purchase Amount (USD)", fontsize=14)

# Save chart
plt.savefig("chart.png", dpi=64, bbox_inches="tight")
plt.close()
